### PR TITLE
Remove Inactive Domains

### PR DESCRIPTION
**Pull request by sr093906**
Inactive domains found in https://github.com/bigdargon/hostsVN/blob/master/hosts
[p.txt](https://github.com/bigdargon/hostsVN/files/7459866/p.txt)

### CODE REVIEW

**Comment by bigdargon** [comment]
@sr093906 Wow!  What tool did you use to check that?

**Comment by sr093906** [comment]
https://pyfunceble.readthedocs.io/en/latest/history.html

I am not 100% sure all the domains are inactive though the results have been tested several times. To play safe, you'd better check them by yourself.

**Comment by bigdargon** [comment]
@sr093906 Can you share how to install and configure the tool? I know this tool, but it is too difficult for my ability! Thank you!

**Comment by sr093906** [comment]
https://pyfunceble.readthedocs.io/en/latest/installation/index.html#stable-version (install python first)
https://pyfunceble.readthedocs.io/en/latest/usage/index.html#global-overview

**Comment by bigdargon** [comment]
I tried installing on Windows, it doesn't seem to work very well! Maybe I need a Linux device. I will try to clean up inactive domains. Please allow me to close this PR. Thank you @sr093906

**Pull request closed without merging**
